#%RAML 1.0
title: Account API

types:
  schemaDataType: !include /data/dataType.raml

/accounts:
  get:
    description: GET all customer's accounts
    headers:
      userId:
      type: integer
    queryParameters:
      type:
        displayName: Account Type
        description: Filter by account type
        type: string
        enum:
          - business
          - personal
        required: false
      name:
        displayName: Account/Person's Name
        description: Filter by account or person's name
        required: false
    responses:
      200:
        body:
          application/json:
            type: schemaDataType[]
            example: !include examples/accountExampleGET.raml
      400:
        body:
          application/json:
            example:
              message: Error getting the data

      
  post:
    description: POST new customer accounts
    headers:
      userId:
      type: integer
    body:
      application/json:
        example: !include examples/accountExamplePOST.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: Accounts created
      400:
        body:
          application/json:
            example:
              message: Error posting the data
