http:
  protocol: "HTTP"
  port: "8081"

client:
  id: "883ed6d76f8248689a3cc5bf1e22f5b7"
  secret: "d434137DfD4c49529590486344B8CaDb"
    
    
account:
  host: "accounts-api-spejeraite.us-e2.cloudhub.io"
  basepath: "/accounts"